import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/Header/Header";
import styles from "./index.module.css";
import { Card } from "~/components/Card";
import { Prompt } from "~/components/Prompt";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Header />
          <Card>
            <Prompt />
          </Card>
        </div>
      </main>
    </>
  );
};

export default Home;
